services:
  web:
    build: .
    ports:
      - "8080:80"
    # volumes:
    #   - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=art_of_tea
      - DB_USER=root
      - DB_PASSWORD=1111
      - DB_PORT=3306
    restart: unless-stopped

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=1111
      - MYSQL_DATABASE=art_of_tea
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1111
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1111"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

volumes:
  mysql_data:
